/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"

// Настройка PD2
void GPIOD_Pin2_Setup(void);

int main(void)
{
	static uint8_t counter = 0;
	DEBUG_MSG("Counter Val: %d \r\n", counter);
	counter++;
	GPIOD_Pin2_Setup();

	while(1) {

	}
}

// Настройка PD2
void GPIOD_Pin2_Setup(void) {

	// Разрешить тактирование порта GPIOD
	SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIODEN);
	// Режим Output
	MODIFY_REG(GPIOD->MODER, GPIO_MODER_MODE2_Msk, GPIO_MODER_MODE2_0);
	// Режим Push-Pull
	CLEAR_BIT(GPIOD->OTYPER, GPIO_OTYPER_OT2);
	// Скорость максимальная
	MODIFY_REG(GPIOD->OSPEEDR, GPIO_OSPEEDR_OSPEED2_Msk, GPIO_OSPEEDR_OSPEED2_0 | GPIO_OSPEEDR_OSPEED2_1);
	// Без подтяжки
	CLEAR_BIT(GPIOD->PUPDR, GPIO_PUPDR_PUPD2_0);
	CLEAR_BIT(GPIOD->PUPDR, GPIO_PUPDR_PUPD2_1);
	// Установить лог. 0 на выходе PD2
	SET_BIT(GPIOD->BSRR, GPIO_BSRR_BR2);
	// Установить лог. 1 на выходе PD2
	//SET_BIT(GPIOD->BSRR, GPIO_BSRR_BS2);
}

// Определение функции вывода на пин SWO
int _write(int file, char *ptr, int len)
{
  (void)file;
  int DataIdx;

  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
	  ITM_SendChar(*ptr++);
  }
  return len;
}
